# Generated by Django 5.2.5 on 2025-08-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreid', models.AutoField(db_column='GenreID', primary_key=True, serialize=False)),
                ('genrename', models.CharField(db_column='GenreName', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.AutoField(db_column='PersonID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=255)),
                ('birthdate', models.DateField(blank=True, db_column='BirthDate', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=100, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=100, unique=True)),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('passwordhash', models.CharField(db_column='PasswordHash', max_length=255)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.AutoField(db_column='MovieID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('releaseyear', models.IntegerField(blank=True, db_column='ReleaseYear', null=True)),
                ('summary', models.TextField(blank=True, db_column='Summary', null=True)),
                ('durationinminutes', models.IntegerField(blank=True, db_column='DurationInMinutes', null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=100, null=True)),
                ('posterurl', models.CharField(blank=True, db_column='PosterURL', max_length=512, null=True)),
                ('tmdbscore', models.DecimalField(blank=True, db_column='TMDbScore', decimal_places=1, max_digits=3, null=True)),
                ('directorid', models.ForeignKey(blank=True, db_column='DirectorID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_movies', to='movies.person')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movies.movie')),
                ('personid', models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='movies.person')),
            ],
            options={
                'db_table': 'movie_actor',
                'unique_together': {('movieid', 'personid')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='movies.MovieActor', to='movies.person'),
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movies.movie')),
                ('genreid', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
            ],
            options={
                'db_table': 'movie_genre',
                'unique_together': {('movieid', 'genreid')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(through='movies.MovieGenre', to='movies.genre'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movies.user')),
                ('score', models.IntegerField(db_column='Score')),
                ('ratedat', models.DateTimeField(blank=True, db_column='RatedAt', null=True)),
                ('movieid', models.ForeignKey(db_column='MovieID', on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'rating',
                'unique_together': {('userid', 'movieid')},
            },
        ),
    ]
